AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mys3store # must be globally unique
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
